<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Equipment;
use App\Models\EquipmentCategory;
use App\Models\Laboratory;

class ChemistryEquipmentSeeder extends Seeder
{
    public function run(): void
    {
        $chemistryLab = Laboratory::where('laboratory_code', 'LAB-001')->first();

        if (!$chemistryLab) {
            $this->command->error('Chemistry Laboratory not found. Please run LaboratorySeeder first.');
            return;
        }

        $equipment = [
            // Chemistry Equipment
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-001',
                'barcode' => 'EQCHEM001',
                'equipment_name' => 'Acid Burette',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-002',
                'barcode' => 'EQCHEM002',
                'equipment_name' => 'Blender',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-003',
                'barcode' => 'EQCHEM003',
                'equipment_name' => 'Disintegration Tester',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-004',
                'barcode' => 'EQCHEM004',
                'equipment_name' => 'Hot Plate',
                'brand' => 'IKA',
                'quantity' => 10,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-005',
                'barcode' => 'EQCHEM005',
                'equipment_name' => 'Water Circulating Pump',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-006',
                'barcode' => 'EQCHEM006',
                'equipment_name' => 'Rotary Evaporator',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-007',
                'barcode' => 'EQCHEM007',
                'equipment_name' => 'Soxhlet Apparatus',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-008',
                'barcode' => 'EQCHEM008',
                'equipment_name' => 'Table Friability Tester',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-009',
                'barcode' => 'EQCHEM009',
                'equipment_name' => 'Tableting Machine',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-010',
                'barcode' => 'EQCHEM010',
                'equipment_name' => 'Water Bath',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-011',
                'barcode' => 'EQCHEM011',
                'equipment_name' => 'Vacuum Pump',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-012',
                'barcode' => 'EQCHEM012',
                'equipment_name' => 'Microwave',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-013',
                'barcode' => 'EQCHEM013',
                'equipment_name' => 'Magnetic Stirrer',
                'brand' => 'IKA',
                'quantity' => 8,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-014',
                'barcode' => 'EQCHEM014',
                'equipment_name' => 'Water Filter',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-015',
                'barcode' => 'EQCHEM015',
                'equipment_name' => 'Desiccator',
                'brand' => 'Pyrex',
                'quantity' => 10,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-CHEM-016',
                'barcode' => 'EQCHEM016',
                'equipment_name' => 'Bunsen Burners',
                'brand' => 'Generic',
                'quantity' => 20,
            ],

            // Glassware
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-017',
                'barcode' => 'EQCHEM017',
                'equipment_name' => 'Boiling Flask',
                'brand' => 'Pyrex',
                'quantity' => 20,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-018',
                'barcode' => 'EQCHEM018',
                'equipment_name' => 'Büchner Funnel',
                'brand' => 'Pyrex',
                'quantity' => 15,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-019',
                'barcode' => 'EQCHEM019',
                'equipment_name' => 'Erlenmeyer Flasks',
                'brand' => 'Pyrex',
                'quantity' => 50,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-020',
                'barcode' => 'EQCHEM020',
                'equipment_name' => 'Reflux Condenser',
                'brand' => 'Pyrex',
                'quantity' => 15,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-021',
                'barcode' => 'EQCHEM021',
                'equipment_name' => 'Round Bottom Flasks',
                'brand' => 'Pyrex',
                'quantity' => 30,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-022',
                'barcode' => 'EQCHEM022',
                'equipment_name' => 'Separatory Funnels',
                'brand' => 'Pyrex',
                'quantity' => 20,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-023',
                'barcode' => 'EQCHEM023',
                'equipment_name' => 'Volumetric Flasks',
                'brand' => 'Pyrex',
                'quantity' => 40,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-024',
                'barcode' => 'EQCHEM024',
                'equipment_name' => 'Test Tubes',
                'brand' => 'Pyrex',
                'quantity' => 100,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-025',
                'barcode' => 'EQCHEM025',
                'equipment_name' => 'Beakers',
                'brand' => 'Pyrex',
                'quantity' => 100,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-026',
                'barcode' => 'EQCHEM026',
                'equipment_name' => 'Graduated Cylinders',
                'brand' => 'Pyrex',
                'quantity' => 50,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-027',
                'barcode' => 'EQCHEM027',
                'equipment_name' => 'Pipettes',
                'brand' => 'Pyrex',
                'quantity' => 100,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-028',
                'barcode' => 'EQCHEM028',
                'equipment_name' => 'Crucibles',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-029',
                'barcode' => 'EQCHEM029',
                'equipment_name' => 'Watch Glasses',
                'brand' => 'Pyrex',
                'quantity' => 50,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-030',
                'barcode' => 'EQCHEM030',
                'equipment_name' => 'Funnels',
                'brand' => 'Pyrex',
                'quantity' => 30,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-CHEM-031',
                'barcode' => 'EQCHEM031',
                'equipment_name' => 'Burettes',
                'brand' => 'Pyrex',
                'quantity' => 30,
            ],

            // Measuring Instruments
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-CHEM-032',
                'barcode' => 'EQCHEM032',
                'equipment_name' => 'Hygrometer',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-CHEM-033',
                'barcode' => 'EQCHEM033',
                'equipment_name' => 'Portable Refractometer',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-CHEM-034',
                'barcode' => 'EQCHEM034',
                'equipment_name' => 'Analytical Balance',
                'brand' => 'Ohaus',
                'quantity' => 5,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-CHEM-035',
                'barcode' => 'EQCHEM035',
                'equipment_name' => 'Double Beam Balance',
                'brand' => 'Ohaus',
                'quantity' => 3,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-CHEM-036',
                'barcode' => 'EQCHEM036',
                'equipment_name' => 'Triple Beam Balance',
                'brand' => 'Ohaus',
                'quantity' => 5,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-CHEM-037',
                'barcode' => 'EQCHEM037',
                'equipment_name' => 'Moisture Analyzer',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-CHEM-038',
                'barcode' => 'EQCHEM038',
                'equipment_name' => 'Polarimeter',
                'brand' => 'Generic',
                'quantity' => 2,
            ],

            // Safety Equipment
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-CHEM-039',
                'barcode' => 'EQCHEM039',
                'equipment_name' => 'Fume Hood',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-CHEM-040',
                'barcode' => 'EQCHEM040',
                'equipment_name' => 'Gas Tank',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-CHEM-041',
                'barcode' => 'EQCHEM041',
                'equipment_name' => 'Eye Wash Station',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-CHEM-042',
                'barcode' => 'EQCHEM042',
                'equipment_name' => 'Fire Extinguishers',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-CHEM-043',
                'barcode' => 'EQCHEM043',
                'equipment_name' => 'Fire Blanket',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-CHEM-044',
                'barcode' => 'EQCHEM044',
                'equipment_name' => 'First Aid Box',
                'brand' => 'Generic',
                'quantity' => 3,
            ],

            // Others
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-045',
                'barcode' => 'EQCHEM045',
                'equipment_name' => 'Mortars and Pestles',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-046',
                'barcode' => 'EQCHEM046',
                'equipment_name' => 'Test Tube Racks',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-047',
                'barcode' => 'EQCHEM047',
                'equipment_name' => 'Trays',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-048',
                'barcode' => 'EQCHEM048',
                'equipment_name' => 'Iron Clamps',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-049',
                'barcode' => 'EQCHEM049',
                'equipment_name' => 'Rubber Stoppers',
                'brand' => 'Generic',
                'quantity' => 50,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-050',
                'barcode' => 'EQCHEM050',
                'equipment_name' => 'Rubber Tubing',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-051',
                'barcode' => 'EQCHEM051',
                'equipment_name' => 'Wash Bottles',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-052',
                'barcode' => 'EQCHEM052',
                'equipment_name' => 'Measuring Cups',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-053',
                'barcode' => 'EQCHEM053',
                'equipment_name' => 'Spatulas',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-054',
                'barcode' => 'EQCHEM054',
                'equipment_name' => 'Wire Gauze',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-055',
                'barcode' => 'EQCHEM055',
                'equipment_name' => 'Tripods',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Furniture',
                'equipment_code' => 'EQ-CHEM-056',
                'barcode' => 'EQCHEM056',
                'equipment_name' => 'Laboratory Tables',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Furniture',
                'equipment_code' => 'EQ-CHEM-057',
                'barcode' => 'EQCHEM057',
                'equipment_name' => 'Cabinets',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Furniture',
                'equipment_code' => 'EQ-CHEM-058',
                'barcode' => 'EQCHEM058',
                'equipment_name' => 'Chairs',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-059',
                'barcode' => 'EQCHEM059',
                'equipment_name' => 'Refrigerator',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-060',
                'barcode' => 'EQCHEM060',
                'equipment_name' => 'Blackboard',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-CHEM-061',
                'barcode' => 'EQCHEM061',
                'equipment_name' => 'Visual Aids',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Electrical Equipment',
                'equipment_code' => 'EQ-CHEM-062',
                'barcode' => 'EQCHEM062',
                'equipment_name' => 'Electric Fans',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-CHEM-063',
                'barcode' => 'EQCHEM063',
                'equipment_name' => 'Emergency Lights',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Computer Equipment',
                'equipment_code' => 'EQ-CHEM-064',
                'barcode' => 'EQCHEM064',
                'equipment_name' => 'CCTV',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
        ];

        foreach ($equipment as $item) {
            $category = EquipmentCategory::where('category_name', $item['category'])->first();

            if (!$category) {
                $this->command->warn("Category '{$item['category']}' not found for {$item['equipment_name']}");
                continue;
            }

            Equipment::updateOrCreate(
                ['equipment_code' => $item['equipment_code']],
                [
                    'barcode' => $item['barcode'],
                    'equipment_name' => $item['equipment_name'],
                    'category_id' => $category->id,
                    'laboratory_id' => $chemistryLab->id,
                    'supplier_id' => null,
                    'brand' => $item['brand'],
                    'model' => null,
                    'serial_number' => null,
                    'purchase_date' => now()->subYear(),
                    'quantity' => $item['quantity'],
                    'available_quantity' => $item['quantity'],
                    'condition' => 'Excellent',
                    'status' => 'Available',
                    'image' => null,
                    'storage_location' => 'Chemistry Storage Room',
                    'description' => $item['equipment_name'] . ' - Chemistry Laboratory Equipment',
                    'remarks' => null,
                ]
            );
        }

        $this->command->info('Chemistry Equipment seeded successfully (' . count($equipment) . ' items).');
    }
}