<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Equipment;
use App\Models\EquipmentCategory;

class EquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $equipment = [

            // =========================================================
            // PHYSICS EQUIPMENT
            // =========================================================

            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000001',
                'barcode' => 'EQ000001',
                'equipment_name' => 'Ammeter',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Electrical Equipment',
                'equipment_code' => 'EQ-000002',
                'barcode' => 'EQ000002',
                'equipment_name' => 'Battery Charger',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000003',
                'barcode' => 'EQ000003',
                'equipment_name' => 'Blower',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000004',
                'barcode' => 'EQ000004',
                'equipment_name' => 'Boyle’s Law Apparatus',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000005',
                'barcode' => 'EQ000005',
                'equipment_name' => 'Centripetal Force Apparatus',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000006',
                'barcode' => 'EQ000006',
                'equipment_name' => 'Force Table',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000007',
                'barcode' => 'EQ000007',
                'equipment_name' => 'Galvanometer',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000008',
                'barcode' => 'EQ000008',
                'equipment_name' => 'Hooke’s Law Apparatus',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000009',
                'barcode' => 'EQ000009',
                'equipment_name' => 'Inclined Plane',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000010',
                'barcode' => 'EQ000010',
                'equipment_name' => 'Iron Stand',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000011',
                'barcode' => 'EQ000011',
                'equipment_name' => 'Linear Expansion Apparatus',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Electrical Equipment',
                'equipment_code' => 'EQ-000012',
                'barcode' => 'EQ000012',
                'equipment_name' => 'Multi-tester',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Electrical Equipment',
                'equipment_code' => 'EQ-000013',
                'barcode' => 'EQ000013',
                'equipment_name' => 'Power Supply',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000014',
                'barcode' => 'EQ000014',
                'equipment_name' => 'Spring Balance',
                'brand' => 'Generic',
                'quantity' => 15,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000015',
                'barcode' => 'EQ000015',
                'equipment_name' => 'Steam Generator',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Electrical Equipment',
                'equipment_code' => 'EQ-000016',
                'barcode' => 'EQ000016',
                'equipment_name' => 'Voltmeter',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Electrical Equipment',
                'equipment_code' => 'EQ-000017',
                'barcode' => 'EQ000017',
                'equipment_name' => 'Digital Multi-tester',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000018',
                'barcode' => 'EQ000018',
                'equipment_name' => 'Pulley',
                'brand' => 'Generic',
                'quantity' => 15,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000019',
                'barcode' => 'EQ000019',
                'equipment_name' => 'Radiometer',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000020',
                'barcode' => 'EQ000020',
                'equipment_name' => 'Recording Timer',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000021',
                'barcode' => 'EQ000021',
                'equipment_name' => 'Ripple Tank',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000022',
                'barcode' => 'EQ000022',
                'equipment_name' => 'Optical Bench',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000023',
                'barcode' => 'EQ000023',
                'equipment_name' => 'Magnifying Glass',
                'brand' => 'Generic',
                'quantity' => 15,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000024',
                'barcode' => 'EQ000024',
                'equipment_name' => 'Meter Sticks',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000025',
                'barcode' => 'EQ000025',
                'equipment_name' => 'Thermometer',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000026',
                'barcode' => 'EQ000026',
                'equipment_name' => 'Trolley',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Physics Equipment',
                'equipment_code' => 'EQ-000027',
                'barcode' => 'EQ000027',
                'equipment_name' => 'Tuning Fork',
                'brand' => 'Generic',
                'quantity' => 10,
            ],

            // =========================================================
            // CHEMISTRY EQUIPMENT
            // =========================================================

            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000028',
                'barcode' => 'EQ000028',
                'equipment_name' => 'Acid Burette',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000029',
                'barcode' => 'EQ000029',
                'equipment_name' => 'Blender',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000030',
                'barcode' => 'EQ000030',
                'equipment_name' => 'Boiling Flask',
                'brand' => 'Pyrex',
                'quantity' => 20,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000031',
                'barcode' => 'EQ000031',
                'equipment_name' => 'Büchner Funnel',
                'brand' => 'Pyrex',
                'quantity' => 15,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000032',
                'barcode' => 'EQ000032',
                'equipment_name' => 'Disintegration Tester',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000033',
                'barcode' => 'EQ000033',
                'equipment_name' => 'Erlenmeyer Flasks',
                'brand' => 'Pyrex',
                'quantity' => 50,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000034',
                'barcode' => 'EQ000034',
                'equipment_name' => 'Hot Plate',
                'brand' => 'IKA',
                'quantity' => 10,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000035',
                'barcode' => 'EQ000035',
                'equipment_name' => 'Hygrometer',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000036',
                'barcode' => 'EQ000036',
                'equipment_name' => 'Reflux Condenser',
                'brand' => 'Pyrex',
                'quantity' => 15,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000037',
                'barcode' => 'EQ000037',
                'equipment_name' => 'Water Circulating Pump',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000038',
                'barcode' => 'EQ000038',
                'equipment_name' => 'Rotary Evaporator',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000039',
                'barcode' => 'EQ000039',
                'equipment_name' => 'Round Bottom Flasks',
                'brand' => 'Pyrex',
                'quantity' => 30,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000040',
                'barcode' => 'EQ000040',
                'equipment_name' => 'Separatory Funnels',
                'brand' => 'Pyrex',
                'quantity' => 20,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000041',
                'barcode' => 'EQ000041',
                'equipment_name' => 'Soxhlet Apparatus',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000042',
                'barcode' => 'EQ000042',
                'equipment_name' => 'Table Friability Tester',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000043',
                'barcode' => 'EQ000043',
                'equipment_name' => 'Tableting Machine',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000044',
                'barcode' => 'EQ000044',
                'equipment_name' => 'Volumetric Flasks',
                'brand' => 'Pyrex',
                'quantity' => 40,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000045',
                'barcode' => 'EQ000045',
                'equipment_name' => 'Water Bath',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000046',
                'barcode' => 'EQ000046',
                'equipment_name' => 'Vacuum Pump',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000047',
                'barcode' => 'EQ000047',
                'equipment_name' => 'Microwave',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000048',
                'barcode' => 'EQ000048',
                'equipment_name' => 'Magnetic Stirrer',
                'brand' => 'IKA',
                'quantity' => 8,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000049',
                'barcode' => 'EQ000049',
                'equipment_name' => 'Water Filter',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000050',
                'barcode' => 'EQ000050',
                'equipment_name' => 'Portable Refractometer',
                'brand' => 'Generic',
                'quantity' => 5,
            ],

            // =========================================================
            // MEDICAL / BIOLOGY EQUIPMENT
            // =========================================================

            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000051',
                'barcode' => 'EQ000051',
                'equipment_name' => 'Blood Pressure Monitor',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000052',
                'barcode' => 'EQ000052',
                'equipment_name' => 'Digital Thermometers',
                'brand' => 'Generic',
                'quantity' => 15,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000053',
                'barcode' => 'EQ000053',
                'equipment_name' => 'Digital Vernier Caliper',
                'brand' => 'Mitutoyo',
                'quantity' => 15,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000054',
                'barcode' => 'EQ000054',
                'equipment_name' => 'Sphygmomanometer',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000055',
                'barcode' => 'EQ000055',
                'equipment_name' => 'Stethoscope',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000056',
                'barcode' => 'EQ000056',
                'equipment_name' => 'Oximeter',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000057',
                'barcode' => 'EQ000057',
                'equipment_name' => 'Micropipette',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Electronic Devices',
                'equipment_code' => 'EQ-000058',
                'barcode' => 'EQ000058',
                'equipment_name' => 'Digital Timer',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Microscopes',
                'equipment_code' => 'EQ-000059',
                'barcode' => 'EQ000059',
                'equipment_name' => 'Microscopes',
                'brand' => 'Olympus',
                'quantity' => 15,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000060',
                'barcode' => 'EQ000060',
                'equipment_name' => 'Centrifuge',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000061',
                'barcode' => 'EQ000061',
                'equipment_name' => 'Laboratory Oven',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000062',
                'barcode' => 'EQ000062',
                'equipment_name' => 'Laboratory Incubator',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000063',
                'barcode' => 'EQ000063',
                'equipment_name' => 'Sterilizer',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000064',
                'barcode' => 'EQ000064',
                'equipment_name' => 'Analytical Balance',
                'brand' => 'Ohaus',
                'quantity' => 5,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000065',
                'barcode' => 'EQ000065',
                'equipment_name' => 'Double Beam Balance',
                'brand' => 'Ohaus',
                'quantity' => 3,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000066',
                'barcode' => 'EQ000066',
                'equipment_name' => 'Triple Beam Balance',
                'brand' => 'Ohaus',
                'quantity' => 5,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000067',
                'barcode' => 'EQ000067',
                'equipment_name' => 'Vortex Mixer',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000068',
                'barcode' => 'EQ000068',
                'equipment_name' => 'Colony Counter',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000069',
                'barcode' => 'EQ000069',
                'equipment_name' => 'Moisture Analyzer',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000070',
                'barcode' => 'EQ000070',
                'equipment_name' => 'Desiccator',
                'brand' => 'Pyrex',
                'quantity' => 10,
            ],
            [
                'category' => 'Measuring Instruments',
                'equipment_code' => 'EQ-000071',
                'barcode' => 'EQ000071',
                'equipment_name' => 'Polarimeter',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000072',
                'barcode' => 'EQ000072',
                'equipment_name' => 'Refrigerator',
                'brand' => 'Generic',
                'quantity' => 3,
            ],

            // =========================================================
            // SAFETY EQUIPMENT
            // =========================================================

            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000073',
                'barcode' => 'EQ000073',
                'equipment_name' => 'Aquarium',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-000074',
                'barcode' => 'EQ000074',
                'equipment_name' => 'Fume Hood',
                'brand' => 'Generic',
                'quantity' => 2,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-000075',
                'barcode' => 'EQ000075',
                'equipment_name' => 'Gas Tank',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-000076',
                'barcode' => 'EQ000076',
                'equipment_name' => 'Fire Extinguishers',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-000077',
                'barcode' => 'EQ000077',
                'equipment_name' => 'Fire Blanket',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-000078',
                'barcode' => 'EQ000078',
                'equipment_name' => 'Eye Wash Station',
                'brand' => 'Generic',
                'quantity' => 3,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-000079',
                'barcode' => 'EQ000079',
                'equipment_name' => 'First Aid Box',
                'brand' => 'Generic',
                'quantity' => 5,
            ],

            // =========================================================
            // ELECTRONICS / FURNITURE
            // =========================================================

            [
                'category' => 'Computer Equipment',
                'equipment_code' => 'EQ-000080',
                'barcode' => 'EQ000080',
                'equipment_name' => 'CCTV',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Furniture',
                'equipment_code' => 'EQ-000081',
                'barcode' => 'EQ000081',
                'equipment_name' => 'Laboratory Tables',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Furniture',
                'equipment_code' => 'EQ-000082',
                'barcode' => 'EQ000082',
                'equipment_name' => 'Cabinets',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Furniture',
                'equipment_code' => 'EQ-000083',
                'barcode' => 'EQ000083',
                'equipment_name' => 'Chairs',
                'brand' => 'Generic',
                'quantity' => 50,
            ],
            [
                'category' => 'Electrical Equipment',
                'equipment_code' => 'EQ-000084',
                'barcode' => 'EQ000084',
                'equipment_name' => 'Electric Fans',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Safety Equipment',
                'equipment_code' => 'EQ-000085',
                'barcode' => 'EQ000085',
                'equipment_name' => 'Emergency Lights',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000086',
                'barcode' => 'EQ000086',
                'equipment_name' => 'Blackboard',
                'brand' => 'Generic',
                'quantity' => 5,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000087',
                'barcode' => 'EQ000087',
                'equipment_name' => 'Visual Aids',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000088',
                'barcode' => 'EQ000088',
                'equipment_name' => 'Anatomy Models',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Microscopes',
                'equipment_code' => 'EQ-000089',
                'barcode' => 'EQ000089',
                'equipment_name' => 'Prepared/Biology Slides',
                'brand' => 'Generic',
                'quantity' => 50,
            ],

            // =========================================================
            // GLASSWARE
            // =========================================================

            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000090',
                'barcode' => 'EQ000090',
                'equipment_name' => 'Glassware',
                'brand' => 'Pyrex',
                'quantity' => 50,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000091',
                'barcode' => 'EQ000091',
                'equipment_name' => 'Test Tubes',
                'brand' => 'Pyrex',
                'quantity' => 100,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000092',
                'barcode' => 'EQ000092',
                'equipment_name' => 'Beakers',
                'brand' => 'Pyrex',
                'quantity' => 100,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000093',
                'barcode' => 'EQ000093',
                'equipment_name' => 'Graduated Cylinders',
                'brand' => 'Pyrex',
                'quantity' => 50,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000094',
                'barcode' => 'EQ000094',
                'equipment_name' => 'Pipettes',
                'brand' => 'Pyrex',
                'quantity' => 100,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000095',
                'barcode' => 'EQ000095',
                'equipment_name' => 'Petri Dishes',
                'brand' => 'Pyrex',
                'quantity' => 50,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000096',
                'barcode' => 'EQ000096',
                'equipment_name' => 'Crucibles',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000097',
                'barcode' => 'EQ000097',
                'equipment_name' => 'Watch Glasses',
                'brand' => 'Pyrex',
                'quantity' => 50,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000098',
                'barcode' => 'EQ000098',
                'equipment_name' => 'Mortars and Pestles',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000099',
                'barcode' => 'EQ000099',
                'equipment_name' => 'Funnels',
                'brand' => 'Pyrex',
                'quantity' => 30,
            ],
            [
                'category' => 'Glassware',
                'equipment_code' => 'EQ-000100',
                'barcode' => 'EQ00100',
                'equipment_name' => 'Burettes',
                'brand' => 'Pyrex',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000101',
                'barcode' => 'EQ000101',
                'equipment_name' => 'Test Tube Racks',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000102',
                'barcode' => 'EQ000102',
                'equipment_name' => 'Trays',
                'brand' => 'Generic',
                'quantity' => 30,
            ],

            // =========================================================
            // LABORATORY TOOLS
            // =========================================================

            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000103',
                'barcode' => 'EQ000103',
                'equipment_name' => 'Dissection Instruments',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000104',
                'barcode' => 'EQ000104',
                'equipment_name' => 'Forceps',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000105',
                'barcode' => 'EQ000105',
                'equipment_name' => 'Scissors',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000106',
                'barcode' => 'EQ000106',
                'equipment_name' => 'Scalpel Handles',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000107',
                'barcode' => 'EQ000107',
                'equipment_name' => 'Dissecting Needles',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Biology Equipment',
                'equipment_code' => 'EQ-000108',
                'barcode' => 'EQ000108',
                'equipment_name' => 'Inoculating Loops',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000109',
                'barcode' => 'EQ000109',
                'equipment_name' => 'Cork Borers',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000110',
                'barcode' => 'EQ000110',
                'equipment_name' => 'Spatulas',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000111',
                'barcode' => 'EQ000111',
                'equipment_name' => 'Wire Gauze',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000112',
                'barcode' => 'EQ000112',
                'equipment_name' => 'Tripods',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Chemistry Equipment',
                'equipment_code' => 'EQ-000113',
                'barcode' => 'EQ000113',
                'equipment_name' => 'Bunsen Burners',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000114',
                'barcode' => 'EQ000114',
                'equipment_name' => 'Iron Clamps',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000115',
                'barcode' => 'EQ000115',
                'equipment_name' => 'Rubber Stoppers',
                'brand' => 'Generic',
                'quantity' => 50,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000116',
                'barcode' => 'EQ000116',
                'equipment_name' => 'Rubber Tubing',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000117',
                'barcode' => 'EQ000117',
                'equipment_name' => 'Wash Bottles',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Others',
                'equipment_code' => 'EQ-000118',
                'barcode' => 'EQ000118',
                'equipment_name' => 'Measuring Cups',
                'brand' => 'Generic',
                'quantity' => 30,
            ],
            [
                'category' => 'Microscopes',
                'equipment_code' => 'EQ-000119',
                'barcode' => 'EQ000119',
                'equipment_name' => 'Microscopy Accessories',
                'brand' => 'Generic',
                'quantity' => 20,
            ],
            [
                'category' => 'Furniture',
                'equipment_code' => 'EQ-000120',
                'barcode' => 'EQ000120',
                'equipment_name' => 'Laboratory Storage Equipment',
                'brand' => 'Generic',
                'quantity' => 10,
            ],
        ];

        foreach ($equipment as $item) {

            $category = EquipmentCategory::where(
                'category_name',
                $item['category']
            )->first();

            if (!$category) {
                $this->command->warn(
                    "Category '{$item['category']}' not found for {$item['equipment_name']}"
                );

                continue;
            }

            Equipment::updateOrCreate(
                [
                    'equipment_code' => $item['equipment_code'],
                ],
                [
                    'barcode' => $item['barcode'],
                    'equipment_name' => $item['equipment_name'],

                    'category_id' => $category->id,

                    'laboratory_id' => 1,
                    'supplier_id' => null,

                    'brand' => $item['brand'],
                    'model' => null,
                    'serial_number' => null,

                    'purchase_date' => now()->subYear(),

                    'quantity' => $item['quantity'],
                    'available_quantity' => $item['quantity'],

                    'condition' => 'Excellent',
                    'status' => 'Available',

                    'image' => null,

                    'storage_location' => 'Storage Room',

                    'description' => $item['equipment_name'],
                    'remarks' => null,
                ]
            );
        }
    }
}