<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="supplier_name">Supplier name</label><input type="text" id="supplier_name" name="supplier_name" value="{{ old('supplier_name', $supplier->supplier_name ?? '') }}" class="form-control admin-form-control @error('supplier_name') is-invalid @enderror" required>@error('supplier_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="contact_person">Contact person</label><input type="text" id="contact_person" name="contact_person" value="{{ old('contact_person', $supplier->contact_person ?? '') }}" class="form-control admin-form-control @error('contact_person') is-invalid @enderror">@error('contact_person')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="email">Supplier email</label><input type="email" id="email" name="email" value="{{ old('email', $supplier->email ?? '') }}" class="form-control admin-form-control @error('email') is-invalid @enderror" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="contact_number">Contact number</label><input type="text" id="contact_number" name="contact_number" value="{{ old('contact_number', $supplier->contact_number ?? '') }}" class="form-control admin-form-control @error('contact_number') is-invalid @enderror">@error('contact_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="status">Status</label><select id="status" name="status" class="form-select admin-form-control" required><option value="Active" @selected(old('status', $supplier->status ?? 'Active') === 'Active')>Active</option><option value="Inactive" @selected(old('status', $supplier->status ?? 'Active') === 'Inactive')>Inactive</option></select></div>
    <div class="col-12"><label class="form-label" for="address">Address</label><textarea id="address" name="address" rows="3" class="form-control admin-form-control">{{ old('address', $supplier->address ?? '') }}</textarea></div>
    <div class="col-12"><label class="form-label" for="remarks">Remarks</label><textarea id="remarks" name="remarks" rows="3" class="form-control admin-form-control">{{ old('remarks', $supplier->remarks ?? '') }}</textarea></div>
    <div class="col-12 text-end mt-2"><a href="{{ route('coordinator.suppliers.index') }}" class="btn btn-outline-secondary me-2">Cancel</a><button type="submit" class="btn btn-primary">{{ isset($supplier) ? 'Save changes' : 'Create supplier' }}</button></div>
</div>
